# PostgreSQL. Versions 8.2 and up are supported.
# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgis
  encoding: unicode
  postgis_extension:  postgis
  #schema_search_path: public, postgis

  database: mywater_development
  username: gmas
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: mywater_test
  min_messages: warning

acceptance:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
